import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider, CssBaseline } from "@mui/material";
import { theme } from "./theme";
import { MainLayout } from "./layouts/MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SAM-MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <AppRouterCacheProvider>
          <body suppressHydrationWarning={true}>
            <MainLayout>
              {children}
            </MainLayout>
          </body>
        </AppRouterCacheProvider>
      </ThemeProvider>
    </html>
  );
}