import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../styles/index.module.scss";
import "../styles/index.module.scss";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { NavbarMobile } from "@/components/header/NavbarMobile";
import { ThemeProvider, CssBaseline } from "@mui/material";

import theme from "./theme/theme";
import "animate.css";

const inter = Inter({ subsets: ["latin"] });
import "../styles/styles.css";
import Providers from "./Provider";
import MainSnackbar from "@/components/snackbar/MainSnackbar";
import ModalInfo from "@/components/snackbar/ModalInfo";
export const metadata: Metadata = {
  title: "SAM-MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <AppRouterCacheProvider>
          <body suppressHydrationWarning={true}>
            <Providers>
              {
                <>
                  {/* {<MainSnackbar />} */}
                  {<ModalInfo />}
                  {<NavbarMobile />}
                  {children}
                </>
              }
            </Providers>
          </body>
        </AppRouterCacheProvider>
      </ThemeProvider>
    </html>
  );
}
