import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "../styles/index.module.scss";
import "../styles/index.module.scss";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { NavbarMobile } from "@/components/header/NavbarMobile";
import { ThemeProvider, CssBaseline } from "@mui/material";
import theme from "./theme";
const inter = Inter({ subsets: ["latin"] });
import '../styles/styles.css'
export const metadata: Metadata = {
  title: "SAM-MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <AppRouterCacheProvider>
          <body suppressHydrationWarning={true}>
            <NavbarMobile />
            {children}
          </body>
        </AppRouterCacheProvider>
      </ThemeProvider>
    </html>
  );
}
